apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: local-live
  name: postgresql
spec:
  selector:
    matchLabels:
      app: posgresql
  template:
    metadata:
      labels:
        app: posgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
          protocol: TCP

        env:
           - name: POSTGRES_PASSWORD
             value: KDcpxbL34qhY5rvy
           - name: POSTGRES_USER
             value: live
           - name: POSTGRES_DB
             value: live_config