apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: posgresql
  template:
    metadata:
      labels:
        app: posgresql
    spec:
      containers:
      - name: postgresql
        image: postgresql:latest
        ports:
        - containerPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webpage
# spec:
#   selector:
#     app: webpage
#   ports:
#   - port: 80
#     targetPort: 80
#   type: LoadBalancer