apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: local-live
spec:
  selector:
    app: posgresql
  ports:
    - name: postgresql  
      protocol: TCP
      port: 5432
      targetPort: 5432
      protocol: TCP

  type: NodePort