apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client2-app
  namespace: live-laminar
spec:
  project: local
  source:
    repoURL: https://github.com/seu-repo/live.git
    path: customer/wl2
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: local-live2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
