apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-laminar
  namespace: client3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live-laminar
  template:
    metadata:
      labels:
        app: live-laminar
    spec:
      containers:
      - name: live-laminar
        image: intelie.azurecr.io/live:3.51.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: live_config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
