apiVersion: v1
kind: Service
metadata:
  name: live-laminar-service
  namespace: local-live2
  labels:
    app: live-laminar
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001 
  selector:
    app: java-app