apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: live-laminar
data:
  default.conf: |
    server {
        listen 80;
        server_name live.laminar.local;
        location / {
            proxy_pass http://live-laminar:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
